services:
  server:
    image: 563748388618.dkr.ecr.us-east-1.amazonaws.com/bia:${TAG}
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB_PORT=5432