name: aws-code-pipeline
services:
  server:
    environment:
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 563748388618.dkr.ecr.us-east-1.amazonaws.com/bia:3653fe4
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
networks:
  default:
    name: aws-code-pipeline_default
name: aws-code-pipeline
services:
  server:
    environment:
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 563748388618.dkr.ecr.us-east-1.amazonaws.com/bia:b5f73ca
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
networks:
  default:
    name: aws-code-pipeline_default
